### PR TITLE
gnome-session-ctl: Fix bitwise logic error

### PR DESCRIPTION
**Pull request by bobby285271**
Cherry-picked from <https://gitlab.gnome.org/GNOME/gnome-session/-/commit/34d1beb4a815d2a60405b2e459ece2f2a88eeac3>

### CODE REVIEW

**Comment by jtojnar** [comment]
Thanks.

**Comment by bobby285271** [comment]
Do we make new release here every time we sync with upstream tag?

Edit: I released https://github.com/nix-community/gnome-session-ctl/releases/tag/47.0.1

**Comment by jtojnar** [comment]
I did in the past but recently I have forgotten about it. Looking at thre previous commits, bumps might be needed for localedir: https://github.com/nix-community/gnome-session-ctl/commit/b0ca0c54c5450bbc16ba1f086a4e3aa8c259b82c

**Comment by bobby285271** [comment]
> bumps might be needed for localedir

Heh, I actually don't understand how this will work, assuming we want it for translations. Later I tried fixing translations and came up with two hacks :upside_down_face:

1. We get translations from `/run/current-system/sw/share` (assuming a `pathsToLink = [ "/share/locale" ]`)

```nix
postPatch = ''
  meson rewrite kwargs set project / version '${gnome-session.version}'
  substituteInPlace meson.build --replace-fail "'@0@-@1@'.format(meson.project_name(), version.split('.')[0])" "'gnome-session-@0@'.format(version.split('.')[0])"
'';

# Ugh.
mesonFlags = [ "--localedir=/run/current-system/sw/share/locale" ];
```

2. We just duplicate the `po` dir.

```diff
diff --git a/meson.build b/meson.build
index ce217ea..68f03ba 100644
--- a/meson.build
+++ b/meson.build
@@ -8,6 +8,7 @@ project(
 
 version = meson.project_version()
 api_name = '@0@-@1@'.format(meson.project_name(), version.split('.')[0])
+session_api_name = api_name
 
 prefix = get_option('prefix')
 localedir = prefix / get_option('localedir')
@@ -39,6 +40,12 @@ foreach define: set_defines
   config_h.set_quoted(define[0], define[1])
 endforeach
 
+i18n = import('i18n')
+fs = import('fs')
+if fs.exists('po')
+  subdir('po')
+endif
+
 configure_file(
   output: 'config.h',
   configuration: config_h
```

```nix
postPatch = ''
  tar -xvJf ${gnome-session.src}
  cp -r gnome-session-${gnome-session.version}/po .
'';
```

**Comment by jtojnar** [comment]
IIRC, gettext uses `XDG_DATA_DIRS` to find the message catalogs, only using the localedir as a ¿fallback?. And `/share` is linked by default on GNOME. But we are not currently installing `gnome-session` to `environment.systemPackages`.

I guess duplicating the podir might be cleanest solution, though.

**Comment by bobby285271** [comment]
We do have gnome-session in `environment.systemPackages` I guess, via `xdg.portal.configPackages` option  .

I can't get translations when I comment out the `mesonFlags`, actually I failed to find how `XDG_DATA_DIRS` is respected (I am looking at [`dcigettext.c`](https://github.com/autotools-mirror/gettext/blob/0d53c885229fc59ca3ce6a8e70fb3f6d59ece361/gettext-runtime/intl/dcigettext.c#L577)) :joy:

**Comment by jtojnar** [comment]
Hmm, looks like it might have just been the ITS files: https://github.com/autotools-mirror/gettext/blob/967e76ba4f72d6e427ddd3bdca1480a978c4a5a8/gettext-tools/src/search-path.c#L116

**Pull request merged**
